### ISSUE TITLE
Mistake in build instructions

### ISSUE THREAD

**Issue by codeinred** [giacomo-b/CppRobotics#10]
This first command here fails to run because the directory `examples/EXAMPLE` doesn't exist:
```bash
cmake -S examples/EXAMPLE -B build/EXAMPLE
cmake --build build/EXAMPLE
```

**Comment by giacomo-b** [comment]
Hi @codeinred, did you run that same exact command? `EXAMPLE` is supposed to be substituted with whatever example you want to compile (see the names of the subfolders).

**Comment by codeinred** [comment]
I did, sorry! I definitely wasn't looking close enough at the README! I re-ran it with one of the directories actually in the examples folder and it worked!

**Comment by giacomo-b** [comment]
Glad it worked! I'm closing this.
