### ISSUE TITLE
The time step should be specified at each call

### ISSUE THREAD

**Issue by giacomo-b** [giacomo-b/CppRobotics#12]
The time step is currently set with a setter method, it would be better if the user had to specify the time step every time the dynamics is propagated, such as in:

`system.PropagateDynamics(input, dt);`

Examples of the problem:

https://github.com/giacomo-b/CppRobotics/blob/bf1965b4e3beb98f731c1915bedbd5069c206aea/examples/pid/main.cpp#L34

https://github.com/giacomo-b/CppRobotics/blob/bf1965b4e3beb98f731c1915bedbd5069c206aea/examples/extended-kalman-filter/main.cpp#L26

Why is this a problem?

1. The user must explicitly call the setter, otherwise they might be propagating the dynamics with the wrong (default) time step
2. Variable time steps are not easily supported

**Comment by kvkpraneeth** [comment]
Hey! I'm interested to contribute starting by taking on this issue. Just to clarify, you do not want the method `SetTimeStep(dt);` to exist and instead specify the time step every time in the while loop, right?

**Comment by giacomo-b** [comment]
Hey thank you so much for your interest! I actually fixed this already offline (I am just waiting for Eigen to be back online before I push my changes, [something weird happened to the repo](https://gitlab.com/libeigen/eigen/-/issues/2336).

If you are interested in contributing though, one great thing you could do is reorganize the LQR so that  the whole loop is not executed inside the class, but the user has control over it. Kind of like what the PID and EKF examples are like.

I'll try to open a detailed issue later on today, so if you are interested feel free to work on that :)
