### ISSUE TITLE
Eigen offline

### ISSUE THREAD

**Issue by kvkpraneeth** [giacomo-b/CppRobotics#15]
Hey! On building the repository, it throws a fatal error of not being able to clone the eigen repository from gitlab. This is because the main eigen repository is offline due to a [technical problem](https://eigen.tuxfamily.org/index.php?title=Main_Page). Can the build process be modified to avoid such things later on? Like maybe maintaining a mirror and cloning that instead?

**Comment by ChrisThrasher** [comment]
These problems are rare enough that it's probably not worth implementing workarounds for them. I've never seen such a repo outage before. If it becomes commonplace then I'm sure someone else will start mirroring Eigen and we can use that.

**Comment by giacomo-b** [comment]
Thank you for pointing this out. This is the first time I see this happening, it is very uncommon. It also means that any project that makes use of git submobule to include Eigen is currently not working.

I agree with @ChrisThrasher on this being so rare that I wouldn't bother mirroring the repo for now. If it became a project in the future, though, we may think about including it directly in the repo.

**Comment by giacomo-b** [comment]
Just adding that [https://gitlab.com/cantonios/eigen](https://gitlab.com/cantonios/eigen) is a recent mirror that you can use instead.
