### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by kvkpraneeth** [giacomo-b/CppRobotics#18]
On building with `cmake` with version **3.16.3**, build process crashes with this output:

```
CMake Error at CMakeLists.txt:56 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "CXX_STANDARD" is not allowed.


-- Configuring incomplete, errors occurred!
```

[Line 56, where the fault points to](https://github.com/giacomo-b/CppRobotics/blob/b179c953d0043388a2a82b4d66493f4412975e91/CMakeLists.txt#L56)

**Comment by giacomo-b** [comment]
Thank you for pointing this out. Indeed, that line is not needed given that the library is now being used as `INTERFACE` since it is header-only. Fixing it now.
