### ISSUE TITLE
Should classes accept `std::size_t` as template parameters instead of `int`?

### ISSUE THREAD

**Issue by giacomo-b** [giacomo-b/CppRobotics#3]
All class templates currently require `int`s as input parameters. This choice was made because [Eigen accepts `int`s as parameters](https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/Matrix.h#L19), and it is straightforward to just forward the value.

Since `int` can be negative, a better solution would be to require `std::size_t` as template parameters. These inputs can then be cast to `int`s and then forwarded to Eigen (e.g. `static_cast<int>(N)`).

**Comment by tomlankhorst** [comment]
Keep these values signed. That way, subtractions will work. If you, at some point, need to calculate the difference between two sizes, you will at least get a valid value. Along the same lines, `std::ssize` is introduced in the cpp standard.

**Comment by giacomo-b** [comment]
That's a very good point you are raising. I was not aware of `std::ssize`, although I don't think it's worth it to require C++20 just because of this. Probably, sticking with `int` is what makes the most sense.

**Comment by codeinred** [comment]
You could just use a [static_assert](https://en.cppreference.com/w/cpp/language/static_assert) to ensure that the parameters are bigger than zero! This runs as a compile time check, not at runtime!

```cpp
// Inside class
static_assert(N > 0, "N must be greater than 0");
