### ISSUE TITLE
Don't Use pragma once

### ISSUE THREAD

**Issue by erichlf** [giacomo-b/CppRobotics#6]
`#pragma once` isn't part of the c++ standard and isn't supported by all compilers, so I would suggest not using it.

**Comment by giacomo-b** [comment]
`#pragma once` isn't part of the standard, but it is very well supported across compilers. As far as I know, [most compilers](https://en.wikipedia.org/wiki/Pragma_once#Portability) have been supporting it for a while now.

Overall, since it is shorter (less code to type) and less error prone (eliminates the risk of name clashes), I think it is convenient to keep using `#pragma once`.

**Comment by erichlf** [comment]
That wiki article is wrong and here is an example of where it is wrong: https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/pragmas/intel-supported-pragma-reference.html

**Comment by erichlf** [comment]
Also, https://stackoverflow.com/a/34884735/1552338

**Comment by tomlankhorst** [comment]
Intel's compilers work fine with `#pragma once`.
Intel had a warning that would show a diagnostic message when using this pragma `-Wpragma-once`, but _that_ has been deprecated. 
This [old thread](https://web.archive.org/web/20160616163742/https://software.intel.com/en-us/articles/cdiag1782) mentions that the pragma is NOT deprecated. 
It's true that pragma once is sensitive to identical header names, but the include guards are in no way better (they have the same weakness).

**Comment by giacomo-b** [comment]
> That wiki article is wrong and here is an example of where it is wrong: https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/pragmas/intel-supported-pragma-reference.html

I believe @tomlankhorst is right. To be fair though, [Intel's compiler doesn't even support all of C++17 features yet](https://en.cppreference.com/w/cpp/compiler_support) (this repo currently uses C++17).

> Also, https://stackoverflow.com/a/34884735/1552338

It looks like some 18 year old bugs [are being referenced in that post](https://www.reddit.com/r/cpp/comments/4cjjwe/comment/d1jmfpg/?utm_source=share&utm_medium=web2x&context=3).

I may be biased, but the advantages I see for `#pragma once` are:
- Less code to type
- No name clashes
- No global namespace pollution
- No risk of spelling a macro wrong and/or forgetting to rename macros when moving files around

The only downside I see is that it may not be able to include the *same* file placed in multiple locations. But then, I don't know why the same file would be placed in multiple locations.

**Comment by giacomo-b** [comment]
Given the several changes that will likely still occur to the project structure, I think `#pragma once` makes more sense for the time being. I am closing this for now, but we can discuss it more down the line if needed.
