### ISSUE TITLE
Should the library be renamed to Control++?

### ISSUE THREAD

**Issue by giacomo-b** [giacomo-b/CppRobotics#8]
As per the title, should we use Control++ (acronym C++) instead of CppRobotics?

I like the generality of CppRobotics, but it is also unoriginal and might convey the wrong idea about the library.

Open to suggestions!

**Comment by codeinred** [comment]
I'd recommend not. CppRobotics is a good name, especially since it was inspired by Python Robotics, and I prefer "CppRobotics" to Control++.

**Comment by giacomo-b** [comment]
Thank you for your feedback. I like the current name, my only concern is that it could be a little misleading (e.g. you could use an EKF for rockets as well, not necessarily for robotics).

**Comment by mayankahm** [comment]
Hi, I would suggest you could use "ClassRobotics" we all know c++ was initially known as c with classes.

**Comment by codeinred** [comment]
What about libctrl (lib for library, ctrl for control)?

**Comment by giacomo-b** [comment]
I would rather not use abbreviations. I would also like the library to reflect its main namespace (e.g. `Control::` in the case of Control++ or ControlPP, `Robotics::` in the case of CppRobotics, etc.)

The main concern is that, if the name includes "robotics", people won't understand that this library can be used for applications such as process control, electronics, drones, etc.

Definitely open to more suggestions.

**Comment by giacomo-b** [comment]
I'm just sticking with the current name for now, as it would make more sense for algorithms such as A* or RRT.

As much as I like Control++, it wouldn't convey the idea of estimation or trajectory planning algorithms.

**Comment by ChrisThrasher** [comment]
A bit late to this issue but I think there's merit in a name that doesn't directly reference robotics, but I'm not sure what a better name would be. Something with "control" does make sense though. `ctrl::` wouldn't be a bad namespace.
